AllCops:
  RunRailsCops: true
  Exclude:
    - 'lib/templates/**/*'
    - 'lib/ftp_sync.rb'

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/LineLength:
  Max: 1200

Metrics/ClassLength:
  Max: 1200

Metrics/MethodLength:
  Max: 1200

Metrics/ModuleLength:
  Max: 1200

Metrics/AbcSize:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Rails/FindBy:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false
