AllCops:
  RunRailsCops: true
  Exclude:
    - 'lib/templates/**/*'

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/LineLength:
  Max: 1200

Metrics/ClassLength:
  Max: 1200

Metrics/MethodLength:
  Max: 1200

Rails/TimeZone:
  Enabled: false

Style/GlobalVars:
  Enabled: false
