doorkeeper_cleanup:
  cron: "<%= Random.rand(0..59) %> <%= Random.rand(3..5) %> * * *"
  class: "Scheduler::DoorkeeperCleanupJob"
  queue: cleanup
  description: "Cleanup expired OAuth tokens"

notification_cleanup:
  cron: "<%= Random.rand(0..59) %> <%= Random.rand(3..5) %> * * *"
  class: "Scheduler::NotificationCleanupJob"
  queue: cleanup
  description: "Cleanup expired notifications"
